version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      dev-dependencies:
        dependency-type: development
  - package-ecosystem: github-actions
    directory: /
    target-branch: dev
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
